version: '3.8'

x-decompiler:
    &default-decompiler-options
        deploy:
            replicas: ${REPLICAS:-1}
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            placement:
                constraints:
                    - "node.role!=manager"
            resources:
                limits:
                    cpus: '1'
                reservations:
                    cpus: '1'

services:
    traefik:
        command:
            - --providers.docker=true
            - --providers.docker.swarmMode=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.web.http.redirections.entrypoint.permanent=true
            - --accesslog
            - --log
            - --certificatesresolvers.myresolver.acme.tlschallenge=true
            - --certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_ACME_EMAIL:?ACME email unset}
            - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
            - --log.level=ERROR
        volumes:
            - "./letsencrypt:/letsencrypt"

    explorer:
        deploy:
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            labels:
                - "traefik.http.routers.explorer.entrypoints=websecure"
                - "traefik.http.routers.explorer.tls.certresolver=myresolver"
        volumes:
            - staticfiles:/opt/decompiler_explorer/staticfiles
            - mediafiles:/opt/decompiler_explorer/media

    binja:
        <<: *default-decompiler-options
    ghidra:
        <<: *default-decompiler-options
    angr:
        <<: *default-decompiler-options
    snowman:
        <<: *default-decompiler-options
    retdec:
        <<: *default-decompiler-options
    recstudio:
        <<: *default-decompiler-options
    boomerang:
        <<: *default-decompiler-options
    reko:
        <<: *default-decompiler-options
    hexrays:
        <<: *default-decompiler-options
    relyze:
        <<: *default-decompiler-options
