version: '3.8'

x-decompiler:
    &default-decompiler-options
        deploy:
            replicas: ${REPLICAS:-1}

services:
    explorer:
        build:
            dockerfile: Dockerfile.dev
        volumes:
            - ./explorer:/opt/decompiler_explorer/explorer
            - ./templates:/opt/decompiler_explorer/templates
            - ./media:/opt/decompiler_explorer/media
            - ./staticfiles:/opt/decompiler_explorer/staticfiles
            - ./static:/opt/decompiler_explorer/static
            - ./decompiler_explorer:/opt/decompiler_explorer/decompiler_explorer
    binja:
        <<: *default-decompiler-options
    ghidra:
        <<: *default-decompiler-options
    angr:
        <<: *default-decompiler-options
    snowman:
        <<: *default-decompiler-options
    retdec:
        <<: *default-decompiler-options
    recstudio:
        <<: *default-decompiler-options
    boomerang:
        <<: *default-decompiler-options
    reko:
        <<: *default-decompiler-options
    hexrays:
        <<: *default-decompiler-options
    dewolf:
        <<: *default-decompiler-options
    relyze:
        <<: *default-decompiler-options
    revng:
        <<: *default-decompiler-options
